---
# Local development environment for a PHP web application
services:
  # ================================= 
  # Live view
  # =================================
  # nginx:
  #   image: nginx:1.31.3-alpine-slim
  #   container_name: dev-loutikdocs
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./dist:/usr/share/nginx/html

  # ==================================
  # Dev view
  # ==================================
  # nginx:
  #   image: dev-loutikdocs:1.0.3
  #   container_name: dev-loutikdocs
  #   ports:
  #     - 8080:8080

  # ===================================
  # Prod view
  # ===================================
  nginx:
    image: ghcr.io/loutik/website-docs:latest
    container_name: prd-loutikdocs
    ports:
      - 8080:8080