server {
    listen 80;
    listen [::]:80;
    server_name _;
    
    # Répertoire des fichiers html
    root /usr/share/nginx/html;
    index index.html;
    
    # Masque de la version de NGINX
    server_tokens off;

    # Empêche les redirections sur les pots
    absolute_redirect off;

    # Redirection favicon
    location = /favicon.ico {
        try_files /favicon.ico =404;
        log_not_found off;
        access_log off;
    }

    # Masque des extensions .html
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # Erreur 404
    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}